"""initial migration

Revision ID: 0f656d2526a7
Revises: 
Create Date: 2023-09-30 15:02:48.944243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f656d2526a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_id', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_users_session_id'), 'users', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_session_id'), table_name='users')
    op.drop_column('users', 'session_id')
    # ### end Alembic commands ###
